# constants.py
MAX_TEXT_LENGTH = 4000
MAX_PROMPT_LENGTH = 8000
MIN_TEXT_FOR_QUIZ = 100
MIN_TEXT_FOR_SUMMARY = 50

MAX_AUDIO_SIZE_MB = 200
MAX_UPLOAD_SIZE_BYTES = 200 * 1024 * 1024

SHINGLE_SIZE = 10
MIN_TEXT_FOR_PLAGIARISM = 100

HANDWRITE_MAX_LINES = 35
HANDWRITE_IMAGE_WIDTH = 800
HANDWRITE_MARGIN = 60
HANDWRITE_LINE_HEIGHT = 50

MINDMAP_MAX_BRANCHES = 8
MINDMAP_MAX_SUB_LINES = 5

ANKI_MAX_CARDS = 50
DIPLOMA_MAX_CHAPTERS = 8
DIPLOMA_MAX_SUBSECTIONS = 8

TASK_POLL_INTERVAL = 2
WORKER_SHUTDOWN_TIMEOUT = 10
CLEANUP_INTERVAL = 3600
TEMP_FILE_RETENTION = 86400

# TTL для кеша источников
CACHE_TTL_DAYS = 7

DEFAULT_RSS_FEEDS = [
    "https://news.yandex.ru/index.rss",
    "https://lenta.ru/rss",
]